services:
    czphpbb.dkp.util.characterlist:
        class: czphpbb\dkp\util\characterlist
        arguments:
            - '@dbal.conn'
            - '@user'
            - '%core.table_prefix%'

    czphpbb.dkp.util.dkp_util:
        class: czphpbb\dkp\util\dkp_util
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'

    czphpbb.dkp.controller:
        class: czphpbb\dkp\controller\main
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@template'
            - '@service_container'
            - '@request'
            - '@user'
            - '%core.table_prefix%'

    czphpbb.dkp.listener.main:
        class: czphpbb\dkp\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    czphpbb.dkp.listener.profile:
        class: czphpbb\dkp\event\profile_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@czphpbb.dkp.util.characterlist'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    czphpbb.dkp.cron.task.dkp:
        class: czphpbb\dkp\cron\task\dkp_decay
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@service_container'
        calls:
            - [set_name, [cron.task.dkp_decay]]
        tags:
            - { name: cron.task }

    czphpbb.dkp.notification.type.dkp:
        class: czphpbb\dkp\notification\type\dkp
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        calls:
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
